### 1. Criar um array com 10 números inteiros aleatórios entre 1 e 50 e calcular a média e o desvio padrão

In [0]:
import numpy as np

random_array = np.random.randint(1, 51, size=10)
media = np.mean(random_array)
media2 = np.average(random_array)
desvio_padrao = np.std(random_array)

print("Array criado: ", random_array)
print("Media calculada com mean: ", media)
print("Media calculada com average: ", media2)
print("Desvio padrao calculado: ", desvio_padrao)

Array criado:  [19 12 35 23  9 43  6  5 23 14]
Media calculada com mean:  18.9
Media calculada com average:  18.9
Desvio padrao calculado:  11.84440796325422


### 2. Criar um array de 10 números aleatórios e calcular a raiz quadrada de todos os valores menores ou iguais a 0,5

In [0]:
import numpy as np
array = np.random.rand(10)
array[array <= 0.5] = np.sqrt(array[array <= 0.5])

print("Array criado: ", array)

Array criado:  [0.52453342 0.72646642 0.85379359 0.65057178 0.68503778 0.23418203
 0.59654529 0.58168653 0.6792109  0.4821893 ]


### 3. Criar uma matriz 3D de tamanho 3x3x3 com valores aleatórios e exibir o valor máximo de cada linha de cada matriz 2D dentro dessa matriz 3D

In [0]:
import numpy as np
# Cria uma matriz 3x3x3 com valores aleatorios
matriz = np.random.rand(3,3,3)

# Exibe o valor maximo de cada linha da matriz 2D dentro da matriz 3D criada
valores_maximos = np.amax(matriz, axis=1)

# Exibe os resultados
print("Matriz 3D criada:\n", matriz, "\n")
print("Valores maximos de cada matriz 2D:\n", valores_maximos)

Matriz 3D criada:
 [[[0.35138731 0.79352239 0.54475898]
  [0.63146725 0.98451177 0.41058407]
  [0.42171535 0.89594693 0.74751527]]

 [[0.9021378  0.56451799 0.53643414]
  [0.51802636 0.96139744 0.90020146]
  [0.04236483 0.55867998 0.28626377]]

 [[0.94289799 0.34569578 0.09635428]
  [0.82303645 0.33951672 0.07592967]
  [0.37875127 0.63985719 0.75197897]]] 

Valores maximos de cada matriz 2D:
 [[0.63146725 0.98451177 0.74751527]
 [0.9021378  0.96139744 0.90020146]
 [0.94289799 0.63985719 0.75197897]]


### 4. Criar uma matriz de tamanho 5x5 com valores aleatórios e subtrair a média de cada linha dessa matriz

In [0]:
import numpy as np
# Cria uma matriz de tamanho 5x5
matriz = np.random.rand(5,5)

# Subtrair a media de cada linha da matriz
media = np.mean(matriz, axis=1)
matriz_linha_media = matriz - media[:, np.newaxis]

print("Matriz original:\n", matriz,"\n")
print("Media de cada linha:\n", media,"\n")
print("Matriz com a media de cada linha subtraida:\n", matriz_linha_media,"\n")

Matriz original:
 [[0.2211417  0.19289926 0.027084   0.43992675 0.06993908]
 [0.35988836 0.23060865 0.89557941 0.95387406 0.30474992]
 [0.79588471 0.99653108 0.61834277 0.3627607  0.05295157]
 [0.08534417 0.95706865 0.1901235  0.34709765 0.70839834]
 [0.90031239 0.83919835 0.4105762  0.19938553 0.77173389]] 

Media de cada linha:
 [0.19019816 0.54894008 0.56529416 0.45760646 0.62424127] 

Matriz com a media de cada linha subtraida:
 [[ 0.03094354  0.0027011  -0.16311416  0.24972859 -0.12025908]
 [-0.18905172 -0.31833143  0.34663933  0.40493398 -0.24419016]
 [ 0.23059055  0.43123691  0.0530486  -0.20253346 -0.5123426 ]
 [-0.37226229  0.49946219 -0.26748296 -0.11050881  0.25079188]
 [ 0.27607112  0.21495708 -0.21366507 -0.42485574  0.14749262]] 



### 5. Criar uma matriz de tamanho 4x4 com valores aleatórios e calcular a média e o desvio padrão das diagonais da matriz

In [0]:
import numpy as np
matriz = np.random.rand(4,4)

diagonal_principal = np.diag(matriz)
diagonal_secundaria = np.diag(np.fliplr(matriz))
media_diagonal = np.mean([diagonal_principal, diagonal_secundaria])
desvio_padrao = np.std([diagonal_principal, diagonal_secundaria])

print("Matriz principal:\n", matriz, "\n")
print("Diagonal principal:\n", diagonal_principal, "\n")
print("Matriz secundaria:\n", diagonal_secundaria, "\n")
print("Media das diagonais:\n", media_diagonal, "\n")
print("Desvio padrao das diagonais:\n", desvio_padrao, "\n")

Matriz principal:
 [[0.13766444 0.7954886  0.31058958 0.847303  ]
 [0.81701019 0.73466806 0.18287858 0.5233917 ]
 [0.35528931 0.56983724 0.54007871 0.03227227]
 [0.86738532 0.88475784 0.7866604  0.20567922]] 

Diagonal principal:
 [0.13766444 0.73466806 0.54007871 0.20567922] 

Matriz secundaria:
 [0.847303   0.18287858 0.56983724 0.86738532] 

Media das diagonais:
 0.510686821861855 

Desvio padrao das diagonais:
 0.2816709274322813 

